-- Extend authenticated desired-state commands with the panel's mounting.
--
-- Orientation describes how a display is physically mounted, so changing it is an
-- operator decision that must reach the device rather than staying a server-side
-- rendering preference. It lived only in devices.orientation_override, and the
-- device never learned of it: the server swapped the rendered geometry while the
-- firmware's surface stayed as built, costing a portrait D1001 480px off the
-- bottom of every frame.
--
-- Generated by drizzle-kit, with IF EXISTS added by hand: migrations here are
-- forward-only and must tolerate a database whose constraint is already absent,
-- and migrate.mjs self-baselines on "already exists" errors, not on "does not
-- exist".
ALTER TABLE "device_configuration_commands" DROP CONSTRAINT IF EXISTS "device_configuration_commands_kind_check";--> statement-breakpoint
ALTER TABLE "device_configuration_commands" ADD CONSTRAINT "device_configuration_commands_kind_check" CHECK ("device_configuration_commands"."kind" IN ('server_url', 'wifi', 'orientation'));