#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Fabian Schmieder. All rights reserved.
#
# Regenerate the firmware logo assets from the SVG source.
#
# The committed .c files only say "DO NOT EDIT — generated by png2lvgl", never
# with which parameters. This script is that missing half: it is the reason the
# assets can be reproduced byte-for-byte instead of guessed at.
#
# Requires: rsvg-convert, python3 + Pillow, and png2lvgl
#           (https://github.com/metaneutrons/png2lvgl — build with `cargo build --release`).
#
#   ./assets/render-logos.sh [path-to-png2lvgl]
#
# ── Why these particular numbers ──────────────────────────────────────
#
# Logo height is 45% of the panel height on every model. That share is not
# arbitrary: e1003 already shipped at 45.3% and looks right, so the rule makes
# the other models match the one that was never broken. e1001/e1002 previously
# used a 318px logo on a 480px panel — 66% — which left no room for the error
# message and pushed it off-screen entirely.
#
#   e1001/e1002   480px high → 216px logo   (1-bit, dark ink on white)
#   e1003        1404px high → 636px logo   (unchanged, already 45.3%)
#   d1001         800px high → 360px logo   (light ink on black)
#
# ── Why these formats ─────────────────────────────────────────────────
#
# indexed1 for the mono e-paper models: two tones, nothing else to preserve.
# indexed8 for d1001: measured against true-color RGB565, indexed8 differs by a
# mean of 0.04/255 (imperceptible) while costing 123 KB instead of 239 KB of
# flash. indexed4 was rejected — 61 KB, but worst-case channel error 92 caused
# visible banding in the magenta gradient.
#
# ── Which SVG for which panel ─────────────────────────────────────────
#
# The suffix means "for a light background", not "a light logo":
#   vellum_logo_light.svg  dark ink  (measured luma 85)  → white e-paper
#   vellum_logo.svg        light ink (measured luma 184) → black d1001 LCD
# Getting this backwards yields a logo that is invisible on its own background.
set -Eeuo pipefail

PNG2LVGL="${1:-$HOME/Source/png2lvgl/target/release/png2lvgl}"
ASSETS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOGOS="${ASSETS}/../firmware/components/vellum_display/logos"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

command -v rsvg-convert >/dev/null || { echo "rsvg-convert not found" >&2; exit 1; }
[[ -x "$PNG2LVGL" ]] || { echo "png2lvgl not found at $PNG2LVGL" >&2; exit 1; }

# Rasterize well above the target size, then trim the transparent margin. The
# viewBox is square (2048x2048) while the artwork is 0.944:1 — the crop is what
# produces that ratio, so trimming must happen before the resize or the logo
# comes out a different shape than the one already shipped.
render() {
  local svg="$1" height="$2" bg="$3" out="$4" mono="$5"
  rsvg-convert -h 2048 "${ASSETS}/${svg}" -o "${WORK}/raw.png"
  python3 - "$WORK/raw.png" "$height" "$bg" "$out" "$mono" <<'PY'
import sys
from PIL import Image
raw, height, bg, out, mono = sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4], sys.argv[5] == "mono"
im = Image.open(raw).convert("RGBA")
im = im.crop(im.split()[-1].getbbox())                 # trim transparent margin
width = round(height * im.size[0] / im.size[1])         # keep the shipped 0.944 ratio
im = im.resize((width, height), Image.LANCZOS)          # LANCZOS: no live scaling on device
flat = Image.new("RGB", (width, height), (255, 255, 255) if bg == "white" else (0, 0, 0))
flat.paste(im, (0, 0), im)                              # flatten onto the panel background
if mono:
    flat = flat.convert("L").point(lambda v: 255 if v > 140 else 0, mode="1")
flat.save(out)
print(f"  {out.rsplit('/', 1)[-1]}  {width}x{height}")
PY
}

echo "e1001/e1002 (480px panel → 216px logo, 1-bit on white)"
render vellum_logo_light.svg 216 white "${ASSETS}/vellum_logo_mono_216px.png" mono
"$PNG2LVGL" "${ASSETS}/vellum_logo_mono_216px.png" -f indexed1 --overwrite \
  -o "${LOGOS}/vellum_logo_mono_216px.c"

echo "d1001 (800px panel → 360px logo, indexed8 on black)"
render vellum_logo.svg 360 black "${ASSETS}/vellum_logo_color_360px.png" color
"$PNG2LVGL" "${ASSETS}/vellum_logo_color_360px.png" -f indexed8 --overwrite \
  -o "${LOGOS}/vellum_logo_color_360px.c"

echo
echo "e1003 keeps vellum_logo_16grey_600px (636px on a 1404px panel = 45.3%)."
echo "Generated .c files are committed; CI does not need png2lvgl."
