// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Fabian Schmieder. All rights reserved.
/**
 * @file test_usb_provisioning_auth.c
 * @brief Cross-language KAT for protected USB re-provisioning.
 *
 * The expected HMAC is generated by the TypeScript server contract. This host
 * mirror pins the exact byte order consumed by vellum_serial.c, so changing the
 * context, MAC encoding, challenge, or payload digest fails before release.
 */
#include "unity_min.h"

#include <openssl/evp.h>
#include <stdint.h>
#include <string.h>

#define AUTH_CONTEXT "vellum-usb-provision-v1\n"

static const uint8_t TOKEN[] =
    "0101010101010101010101010101010101010101010101010101010101010101";
static const uint8_t CHALLENGE[16] = {
    0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77,
    0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff,
};
static const uint8_t EXPECTED[32] = {
    0x41, 0xd1, 0x8d, 0x94, 0xf8, 0x2f, 0x33, 0xe1,
    0x3c, 0x68, 0x0c, 0x62, 0xa1, 0xe7, 0x3c, 0xcc,
    0x4f, 0x86, 0xd7, 0x21, 0x08, 0x96, 0xe8, 0xb6,
    0x44, 0xb5, 0xf2, 0x25, 0x95, 0x3b, 0xc0, 0x53,
};

static int sign_contract(const char mac[12], const uint8_t challenge[16],
                         const uint8_t digest[32], uint8_t out[32])
{
    uint8_t message[(sizeof(AUTH_CONTEXT) - 1) + 12 + 16 + 32];
    size_t pos = 0;
    memcpy(message + pos, AUTH_CONTEXT, sizeof(AUTH_CONTEXT) - 1);
    pos += sizeof(AUTH_CONTEXT) - 1;
    memcpy(message + pos, mac, 12); pos += 12;
    memcpy(message + pos, challenge, 16); pos += 16;
    memcpy(message + pos, digest, 32); pos += 32;

    EVP_PKEY *key = EVP_PKEY_new_raw_private_key(EVP_PKEY_HMAC, NULL, TOKEN,
                                                  sizeof(TOKEN) - 1);
    EVP_MD_CTX *ctx = EVP_MD_CTX_new();
    size_t out_len = 32;
    int ok = key && ctx && EVP_DigestSignInit(ctx, NULL, EVP_sha256(), NULL, key) == 1 &&
             EVP_DigestSign(ctx, out, &out_len, message, pos) == 1 && out_len == 32;
    EVP_MD_CTX_free(ctx);
    EVP_PKEY_free(key);
    return ok;
}

void test_usb_auth_matches_server_vector(void)
{
    uint8_t digest[32], actual[32];
    memset(digest, 0xff, sizeof(digest));
    TEST_ASSERT_TRUE(sign_contract("A1B2C3D4E5F6", CHALLENGE, digest, actual));
    TEST_ASSERT_EQUAL_MEMORY(EXPECTED, actual, sizeof(actual));
}

void test_usb_auth_is_bound_to_every_field(void)
{
    uint8_t digest[32], changed_challenge[16], actual[32];
    memset(digest, 0xff, sizeof(digest));
    memcpy(changed_challenge, CHALLENGE, sizeof(changed_challenge));
    changed_challenge[0] ^= 1;
    TEST_ASSERT_TRUE(sign_contract("A1B2C3D4E5F6", changed_challenge, digest, actual));
    TEST_ASSERT_FALSE(memcmp(EXPECTED, actual, sizeof(actual)) == 0);

    digest[31] ^= 1;
    TEST_ASSERT_TRUE(sign_contract("A1B2C3D4E5F6", CHALLENGE, digest, actual));
    TEST_ASSERT_FALSE(memcmp(EXPECTED, actual, sizeof(actual)) == 0);

    digest[31] ^= 1;
    TEST_ASSERT_TRUE(sign_contract("A1B2C3D4E5F7", CHALLENGE, digest, actual));
    TEST_ASSERT_FALSE(memcmp(EXPECTED, actual, sizeof(actual)) == 0);
}

void run_usb_provisioning_auth_tests(void)
{
    RUN_TEST(test_usb_auth_matches_server_vector);
    RUN_TEST(test_usb_auth_is_bound_to_every_field);
}
