// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Fabian Schmieder. All rights reserved.
/**
 * @file test_ota_signature.c
 * @brief KAT for the OTA Ed25519 signature-verify contract.
 *
 * Mirrors verify_one_key() in ota_manager.c: a raw 32-byte Ed25519 public key
 * verifies a 64-byte PURE-EdDSA signature over the raw 32-byte SHA-256 image
 * digest. The device uses PSA (psa_verify_message / PSA_ALG_PURE_EDDSA); this
 * host test uses OpenSSL, which implements the same RFC 8032 Ed25519. The vector
 * is generated by scripts/gen_kat.mjs (server-side signer) so a change to either
 * the signing contract or the verify path breaks this test.
 */
#include "unity_min.h"
#include "kat_util.h"

#include <openssl/evp.h>
#include <string.h>

/* Golden vector (see scratchpad/gen_kat.mjs → ED25519_KAT). */
static const char *PUBKEY_B64 = "F8t5+ytBIPKx7GXkGY1uCLKOgT/rAeSkAIObheGAgM4=";
static const char *SIG_B64 =
    "tJtLOJmhOVrtL2vMa/6LB6opOQ0xQvCKan6hc/1+poxHOwCRbqa6WCK0rAsdCs8Pte7GBmxl8yGvXSa1ty9eDQ==";
/* Raw 32-byte SHA-256 image digest the signature covers. */
static const uint8_t DIGEST[32] = {
    0xfc, 0x89, 0x07, 0x66, 0xb7, 0x16, 0xee, 0x42, 0xb5, 0x6c, 0x3e, 0x91,
    0x58, 0x80, 0xaf, 0xdc, 0x3d, 0x2a, 0xa4, 0x84, 0xf9, 0x5b, 0x9f, 0x9a,
    0xb3, 0x2d, 0x52, 0x3d, 0x75, 0x86, 0xe0, 0x53,
};

/* Mirror of verify_one_key(): true iff `sig` verifies over `msg` under `pub`. */
static int ed25519_verify(const uint8_t *pub, size_t publen, const uint8_t *sig,
                          size_t siglen, const uint8_t *msg, size_t msglen)
{
    if (publen != 32 || siglen != 64) return 0;
    EVP_PKEY *pk = EVP_PKEY_new_raw_public_key(EVP_PKEY_ED25519, NULL, pub, publen);
    if (!pk) return 0;
    EVP_MD_CTX *ctx = EVP_MD_CTX_new();
    int ok = 0;
    if (ctx && EVP_DigestVerifyInit(ctx, NULL, NULL, NULL, pk) == 1) {
        ok = (EVP_DigestVerify(ctx, sig, siglen, msg, msglen) == 1);
    }
    EVP_MD_CTX_free(ctx);
    EVP_PKEY_free(pk);
    return ok;
}

void test_ed25519_valid_signature(void)
{
    uint8_t pub[32], sig[64];
    TEST_ASSERT_EQUAL_INT(32, b64_decode(PUBKEY_B64, pub, sizeof(pub)));
    TEST_ASSERT_EQUAL_INT(64, b64_decode(SIG_B64, sig, sizeof(sig)));
    TEST_ASSERT_TRUE(ed25519_verify(pub, 32, sig, 64, DIGEST, 32));
}

void test_ed25519_tampered_digest_rejected(void)
{
    uint8_t pub[32], sig[64];
    b64_decode(PUBKEY_B64, pub, sizeof(pub));
    b64_decode(SIG_B64, sig, sizeof(sig));
    uint8_t bad[32];
    memcpy(bad, DIGEST, 32);
    bad[0] ^= 0x01; /* flip one bit of the signed message */
    TEST_ASSERT_FALSE(ed25519_verify(pub, 32, sig, 64, bad, 32));
}

void test_ed25519_tampered_signature_rejected(void)
{
    uint8_t pub[32], sig[64];
    b64_decode(PUBKEY_B64, pub, sizeof(pub));
    b64_decode(SIG_B64, sig, sizeof(sig));
    sig[10] ^= 0x80; /* corrupt the signature */
    TEST_ASSERT_FALSE(ed25519_verify(pub, 32, sig, 64, DIGEST, 32));
}

void test_ed25519_wrong_key_rejected(void)
{
    uint8_t pub[32], sig[64];
    b64_decode(PUBKEY_B64, pub, sizeof(pub));
    b64_decode(SIG_B64, sig, sizeof(sig));
    pub[0] ^= 0x01; /* not the signer's key */
    TEST_ASSERT_FALSE(ed25519_verify(pub, 32, sig, 64, DIGEST, 32));
}

void run_ota_signature_tests(void)
{
    RUN_TEST(test_ed25519_valid_signature);
    RUN_TEST(test_ed25519_tampered_digest_rejected);
    RUN_TEST(test_ed25519_tampered_signature_rejected);
    RUN_TEST(test_ed25519_wrong_key_rejected);
}
